version: '3'
services:
  mongodb:
    image: 'mongo:latest'
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile.dev
      context: ./
    ports:
      - 3005:3005
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
